### ISSUE TITLE
Support a template bean definition for the IdentifiableBeanPostProcessor

### ISSUE THREAD

**Issue by philsmart** [iay/md-validator#36]
The IdentifiableBeanPostProcessor bean is directly defined in validator configuration files by its fully-qualified class name (FQCN). The FQCN has changed between MDA 0.9 and 0.10 due to backend library changes (from Shib java-extensions to shib-shared). Rather than requiring different validator configurations for each MDA version just to change the FQCN of this bean, changes to the FQCN (or even the class itself) can be abstracted from the configuration by using a template bean definition with a suitable identifier defined in a parent context that belongs to the specific MDA being used (unlike the FQCN, the identifier should remain stable).

For MDA 0.10.0, this template bean will exist in the `beans.xml` file of the MDA itself (see [MDA-293](https://shibboleth.atlassian.net/browse/MDA-293)). Once added to the upstream MDA, on the `main` branch of `md-validator`, we can replace any existing IdentifiableBeanPostProcessor definitions with a bean definition that uses the parent template bean.

For MDA 0.9, there is no central `beans.xml` file and so the work in [MDA-293](https://shibboleth.atlassian.net/browse/MDA-293) will need to be directly applied to the [mda-beans.xml](https://github.com/iay/md-validator/blob/0.9/src/main/resources/mda-beans.xml) file of the `mda-validator`'s 0.9 branch. As with 0.10.0, once the parent bean has been added, we will also need to replace any existing IdentifiableBeanPostProcessor definitions with a bean definition that uses the parent template bean.

**Comment by philsmart** [comment]
The work items as I see it:

1. For the 0.9 branch, the template parent bean can be taken from [MDA-293](https://shibboleth.atlassian.net/browse/MDA-293) and added to [mda-beans.xml](https://github.com/iay/md-validator/blob/0.9/src/main/resources/mda-beans.xml).
2. The IdentifiableBeanPostProcessor bean in [common-beans.xml](https://github.com/iay/md-validator/blob/0.9/src/main/resources/common-beans.xml) in both `main` and `0.9` md-validator branches will need updating to use the new parent bean.
3. All individual validator configuration files for both `main` and `0.9` md-validator branches will need updating to use the new parent bean.
4. Any other reference to the IdentifiableBeanPostProcessor should also be updated.

**Comment by iay** [comment]
Done on main branch, commit f5c82ee3695db60b28b95d706dd0e5fdfe95cd76.

**Comment by iay** [comment]
Done on the 0.9 branch, commit 5505cb96ec8805a8d6b937218c60292eb1dca68c.

This is more or less the same other than also defining the bean in `mda-beans.xml`.
